Public Class Changelog
    Private Sub MephButton1_Click(sender As Object, e As EventArgs) Handles MephButton1.Click
        Close()
        GMCommands.Show()
    End Sub

    Private Sub MephComboBox1_SelectedIndexChanged(sender As Object, e As EventArgs) Handles MephComboBox1.SelectedIndexChanged
        If MephComboBox1.SelectedItem = "V1.0.0" Then
            Label1.Text = "V1.0.0"
            Label2.Text = "-------------------------------------------------------------------------"
            Label3.Text = "-Added Changelog"
            Label4.Text = "-Added Version to the Left corner"
            Label5.Text = "-Added the Command list"
            Label6.Text = "-Added YouTube and Twitch link to Picture"
            Label7.Text = "-Removed the - □ x and added a Close/Back button"
            Label8.Text = "-Added Credits"
            Label9.Text = "-Added Icon"
            Label10.Text = "-Added $AddMonster"
            Label11.Text = "-Added $AddPartner"
            Label12.Text = "-Added $AddPet"
            Label13.Text = "-Added $AddPortal"
            Label14.Text = "-Added PortalType with Pictures"
            Label15.Text = "-Added $AddShellEffect"
            Label16.Text = "----------------------------------------------------"
            Label17.Text = "29.10.2017"
            Label18.Text = ""
            Label19.Text = ""
            Label20.Text = ""
        End If

        If MephComboBox1.SelectedItem = "V1.0.1" Then
            Label1.Text = "V1.0.1"
            Label2.Text = "-------------------------------------------------------------------------"
            Label3.Text = "-Added $Bank Helper"
            Label4.Text = "-Added $Bank Help"
            Label5.Text = "-Added $Bank Balance"
            Label6.Text = "-Added $Bank Deposit"
            Label7.Text = "-Added $Bank Withdraw"
            Label8.Text = "-Added $Bank Send"
            Label9.Text = "-Added Changelog Selection Box"
            Label10.Text = "-Added $AddSkill"
            Label11.Text = "----------------------------------------------------"
            Label12.Text = "30.10.2017"
            Label13.Text = ""
            Label14.Text = ""
            Label15.Text = ""
            Label16.Text = ""
            Label17.Text = ""
            Label18.Text = ""
            Label19.Text = ""
            Label20.Text = ""
        End If

        If MephComboBox1.SelectedItem = "V1.0.2" Then
            Label1.Text = "V1.0.2"
            Label2.Text = "-------------------------------------------------------------------------"
            Label3.Text = "-Edited the PortalTypes with a Dropdown menu"
            Label4.Text = "-Added $ArenaWings"
            Label5.Text = "-Added $Backpack"
            Label6.Text = "-Added $Ban"
            Label7.Text = "-Added Icon for the .exe"
            Label8.Text = "-Added $BlockExp"
            Label9.Text = "-Added $BlockFExp"
            Label10.Text = "-Added Function to all Buttons"
            Label11.Text = "-Added $BlockPM"
            Label12.Text = "-Added $BlockRep"
            Label13.Text = "-Added $Buff"
            Label14.Text = "-Added $ChangeClass"
            Label15.Text = "-Added Class Pictures"
            Label16.Text = "-Added $ChangeDignity"
            Label17.Text = "-Added DignityIcons"
            Label18.Text = "-Changed PortalType Pictures"
            Label19.Text = "----------------------------------------------------"
            Label20.Text = "31.10.2017"
        End If


        If MephComboBox1.SelectedItem = "V1.0.3" Then
            Label1.Text = "V1.0.3"
            Label2.Text = "-------------------------------------------------------------------------"
            Label3.Text = "-Added $ChangeRep"
            Label4.Text = "-Added Reputation Icons"
            Label5.Text = "----------------------------------------------------"
            Label6.Text = "-Fixed Changelog Bug (V1.0.0 was clean at first)"
            Label7.Text = "----------------------------------------------------"
            Label8.Text = "01.11.2017"
            Label9.Text = ""
            Label10.Text = ""
            Label11.Text = ""
            Label12.Text = ""
            Label13.Text = ""
            Label14.Text = ""
            Label15.Text = ""
            Label16.Text = ""
            Label17.Text = ""
            Label18.Text = ""
            Label19.Text = ""
            Label20.Text = ""
        End If

        If MephComboBox1.SelectedItem = "V1.0.4" Then
            Label1.Text = "V1.0.4"
            Label2.Text = "-------------------------------------------------------------------------"
            Label3.Text = "-Added $ChangeSex"
            Label4.Text = "----------------------------------------------------"
            Label5.Text = "03.11.2017"
            Label6.Text = ""
            Label7.Text = ""
            Label8.Text = ""
            Label9.Text = ""
            Label10.Text = ""
            Label11.Text = ""
            Label12.Text = ""
            Label13.Text = ""
            Label14.Text = ""
            Label15.Text = ""
            Label16.Text = ""
            Label17.Text = ""
            Label18.Text = ""
            Label19.Text = ""
            Label20.Text = ""
        End If

        If MephComboBox1.SelectedItem = "V1.0.5" Then
            Label1.Text = "V1.0.5"
            Label2.Text = "-------------------------------------------------------------------------"
            Label3.Text = "-Close the Main window on other buttons"
            Label4.Text = "-Fixed Close on ''BlockFExp''"
            Label5.Text = "-Made the code an Overview"
            Label6.Text = "-Added to every ''Back'' button the code for Showing the Main Window"
            Label7.Text = "-Changed the Picture"
            Label8.Text = "-Changed Icon"
            Label9.Text = "-Added Command using"
            Label10.Text = "-Added Injection for the Server"
            Label11.Text = "-Added KeySender"
            Label12.Text = "-------------------------------------------------------------------------"
            Label13.Text = "-Bug : NosTale is not reacting to SendKeys"
            Label14.Text = "-Deactivated the Command Using Button"
            Label15.Text = "-------------------------------------------------------------------------"
            Label16.Text = "08.11.2017"
            Label17.Text = ""
            Label18.Text = ""
            Label19.Text = ""
            Label20.Text = ""
        End If

        If MephComboBox1.SelectedItem = "V1.0.6" Then
            Label1.Text = "V1.0.6"
            Label2.Text = "-------------------------------------------------------------------------"
            Label3.Text = "-Window Expansion for Commands"
            Label4.Text = "-Added Buttons for Commands"
            Label5.Text = "-► Command Use"
            Label6.Text = "-► Monster Vnums"
            Label7.Text = "-► Item Vnums"
            Label8.Text = "-► Map ID's"
            Label9.Text = "-► Collaps Window"
            Label10.Text = "-► Skill Vnums"
            Label11.Text = "-Added Dropdown Menu for Commands"
            Label12.Text = "-Added Command Line"
            Label13.Text = "-------------------------------------------------------------------------"
            Label14.Text = "12.11.2017"
            Label15.Text = ""
            Label16.Text = ""
            Label17.Text = ""
            Label18.Text = ""
            Label19.Text = ""
            Label20.Text = ""
        End If

    End Sub
End Class